# Service Name
service: lambda-s3-example-${opt:stage, 'dev'}

# plugins
plugins:
  - serverless-offline
  - serverless-s3-local

custom:
  stage: ${opt:stage, self:provider.stage}
  bucket: lambda-s3-example-bucket-local
  s3:
    host: localhost
    port: 8000
    directory: ./s3-local

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  region: ${file(./yml/${opt:stage, 'dev'}.yml):provider.region, 'eu-west-1'}
  environment:
    ${file(./yml/${opt:stage, 'dev'}.yml):provider.environment}

package:
  individually: true
  exclude:
    - ./**

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:stage, self:custom.bucket}

functions:
  upload:
    handler: index.upload
    events:
      - httpApi:
          path: /upload
          method: post
    package:
      include:
        - index.js          
  list:
    handler: index.list
    events:
      - httpApi:
          path: /list
          method: get
    package:
      include:
        - index.js          

