# Service Name
service: lambda-dynamodb-stream-example-${opt:stage, 'dev'}

# plugins
plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-offline-dynamodb-stream
  
# Custom
custom: 
  ${file(./environments/${opt:stage, 'dev'}.yml):custom}

# Provider
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  region: ${file(./environments/${opt:stage, 'dev'}.yml):provider.region, 'eu-west-1'}
  environment:
    ${file(./environments/${opt:stage, 'dev'}.yml):provider.environment}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  layers:
    - { Ref: DynamodbStreamExampleLambdaLayer }

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./src/lib/**

# Layers
layers:
  dynamodbStreamExample:
    path: lambda-layer-dir
    package:
      include:
        - ./**

# Functions
functions:
  - ${file(./environments/functions/create.yml)}
  - ${file(./environments/functions/list.yml)}
  - ${file(./environments/functions/dynamoDBStreamCallback.yml)}


# Resources
resources:
  # Stream trigger table
  - ${file(./environments/tables/table_dynamodb_stream_example_ping.yml)}
  # Receive stream data table
  - ${file(./environments/tables/table_dynamodb_stream_example_pong.yml)}
