# Service Name
service: http-api-dynamodb-example-${opt:stage, 'dev'}

# Plugins
plugins:
  - serverless-offline
  - serverless-dynamodb-local

# Custom
custom: 
  ${file(./environments/${opt:stage, 'dev'}.yml):custom}

# Provider
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  region: ${file(./environments/${opt:stage, 'dev'}.yml):provider.region, 'eu-west-1'}
  environment:
    ${file(./environments/${opt:stage, 'dev'}.yml):provider.environment}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  layers:
    - { Ref: DynamodbExampleLambdaLayer }

# Package
package:
  individually: true
  exclude:
    - ./**
  include:
    - ./src/lib/**

# Layers
layers:
  dynamodbExample:
    path: lambda-layer-dir
    package:
      include:
        - ./**

# Functions
functions:
  - ${file(./environments/functions/create.yml)}
  - ${file(./environments/functions/list.yml)}

# Resources
resources:
  - ${file(./environments/tables/table_example.yml)}
