# Service Name
service: http-api-dynamodb-example-${opt:stage, 'dev'}

# plugins
plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    stages:
      - ${opt:stage, self:provider.stage}
    start:
      port: 8000
      inMemory: false
      migrate: true
      seed: false
    seed:
      domain:
        sources:
          - table: table_example
            sources: [./local/db/seed/table_example.json]

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  region: ${file(./yml/${opt:stage, 'dev'}.yml):provider.region, 'eu-west-1'}
  environment:
    ${file(./yml/${opt:stage, 'dev'}.yml):provider.environment}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  layers:
    - { Ref: DynamodbExampleLambdaLayer }
package:
  individually: true
  exclude:
    - ./**
  include:
    - ./lib/**
layers:
  dynamodbExample:
    path: lambda-layer-dir
    package:
      include:
        - ./**

functions:
  create:
    handler: index.create
    events:
      - httpApi:
          path: /create
          method: post
    package:
      include:
        - index.js          
  list:
    handler: index.list
    events:
      - httpApi:
          path: /list
          method: get
    package:
      include:
        - index.js          
resources:
  - ${file(./local/db/table/table_example.yml)}
