custom:
  bucket: lambda-s3-example-bucket-local
  s3:
    host: localhost
    port: 8000
    directory: ./s3-local
provider:
  region: eu-west-1
  environment: 
    testLambdaVariable: Lambda Environment "${opt:stage, 'local'}" Variable
