provider:
  region: eu-west-1
  environment: 
    testLambdaVariable: Lambda Environment "${opt:stage, 'local'}" Variable
custom:
  stage: ${opt:stage, self:provider.stage}
  accessKeyId: "S3RVER"
  secretAccessKey: "S3RVER"
  s3:
    protocol: 'http://'
    host: localhost
    port: 8000
    directory: ./s3-local
    bucketName: lambda-s3-example-${opt:stage, 'dev'}
