# Service Name
service: http-api-example-${opt:stage, 'dev'}

# plugins
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${file(./yml/${opt:stage, 'dev'}.yml):provider.region, 'eu-west-1'}
  environment:
    ${file(./yml/${opt:stage, 'dev'}.yml):provider.environment}

package:
  individually: true

functions:
  httpEvent:
    handler: index.main_handler
    name: httpApi
    events:
      - httpApi:
          path: /httpApi
          method: get